### ISSUE TITLE
'else' not implemented

### ISSUE THREAD

**Issue by rodneyxr** [rodneyxr/fileflowanalysis#1]
When trying use a script with `else` I get a not implement exception.

**Example script:**
```
$x0 = 'a';
$x1 = 'b';
if (other) {
    $x0 = $x1;
} else {
    $x1 = $x0;
}
```

**Exception:**
`edu.utsa.fileflow.analysis.AnalysisException: Analyzer.java: Not implemented: else`

**Comment by stevenpetroff** [comment]
This is unnaceptable. I want it fixed by next Friday.

On Mar 22, 2017 2:34 PM, "Rodney Rodriguez" <notifications@github.com>
wrote:

When trying use a script with else I get a not implement exception.

*Example script:*

$x0 = 'a';
$x1 = 'b';
if (other) {
    $x0 = $x1;
} else {
    $x1 = $x0;
}

*Exception:*
edu.utsa.fileflow.analysis.AnalysisException: Analyzer.java: Not
implemented: else

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rodneyxr/fileflowanalysis/issues/1>, or mute the thread

**Comment by stevenpetroff** [comment]
I've been waiting for this fix for a while. Thanks!
